webtalk_init -webtalk_dir /proj/xhdhdstaff1/harinik/AWSQ/AmazonFreeRTOS_ForHelloDemo/AmazonFreeRTOS/demos/xilinx/microzed/SDK/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-09-10 20:12:57" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "1_2_4_3" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fttfiojp9m4cqhdbc7n21f02gj" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2687W v3 @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1205.003 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.655 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1536566121000" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key hwid -value "1532953718000" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key bspid -value "1534407215000" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key projSize -value "2334.46875" -context "sdk\\\\application/1536566121000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1536590577503"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1536590577503"
webtalk_add_data -client sdk -key BootgenCount -value "13" -context "sdk\\\\bsp/1536590577503"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1536590577503"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1536590577503"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1536590577503"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1536590577503"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1536590577503"
webtalk_transmit -clientid 568422134 -regid "1_2_4_3" -xml /proj/xhdhdstaff1/harinik/AWSQ/AmazonFreeRTOS_ForHelloDemo/AmazonFreeRTOS/demos/xilinx/microzed/SDK/webtalk/usage_statistics_ext_sdk.xml -html /proj/xhdhdstaff1/harinik/AWSQ/AmazonFreeRTOS_ForHelloDemo/AmazonFreeRTOS/demos/xilinx/microzed/SDK/webtalk/usage_statistics_ext_sdk.html -wdm /proj/xhdhdstaff1/harinik/AWSQ/AmazonFreeRTOS_ForHelloDemo/AmazonFreeRTOS/demos/xilinx/microzed/SDK/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
